# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "bitkitchen-tf-state"
    encrypt = true
    key     = "nodejs-skeleton/apigw-private-integration/."
    region  = "eu-west-1"
  }
}
